### ISSUE TITLE
FB_CanItfHelper.mCheckSetup Size check incorrect if using CX2500-M510

### ISSUE THREAD

**Issue by CTimmermans1** [Beckhoff-USA-Community/CanItfHelper#1]
Inside the mCheckSetup, the size is validated against 146 bytes for 29Bit mode (ST_RxCanQueue_29bit and ST_TxCanQueue_29bit), however with a CX2500-M510, the process image data size is 168.0 bytes due to the additional size of the TxMessages and addition of the TransactionNumber by comparison to the EL6751 setup.

**Comment by CameronJohnson556** [comment]
handled see commits sha "96bf2e4a710411acf0d87b7b4d199a8727764407" and "b2e8d5530af305bdf1de124693df8ec32b075e19"
